### ISSUE TITLE
Server Side Error

### ISSUE THREAD

**Issue by TinuFluff** [notcharliee/phase#10]
**Describe the bug**
dashboard/modules/auto-roles page has a server side error
**To Reproduce**
Go to the auto role module

**Expected behaviour**
Page give auto role module 
**Screenshots**
![Screenshot 2024-02-24 214753](https://github.com/notcharliee/phase/assets/139096252/0faaa575-712d-4b66-b5d7-6c6eea98bcba)

**Comment by notcharliee** [comment]
I've checked the logs and it seems to be a strange edge case. Can you try refreshing?

**Comment by TinuFluff** [comment]
I saw it for a second then it goes right to server side issue

**Comment by notcharliee** [comment]
I've deployed a fix in 24d12d5
Let me know if it's still broken
