### ISSUE TITLE
Make some staff changes commands.

### ISSUE THREAD

**Issue by MrAC850** [notcharliee/phase#4]
Make some features like:

/Promote
/Warn
/Demote

For staff, so if a staff member does well, you can do the promote command and it will notify the staff member that they are being promoted.

Warn, if a staff member breaks some rules ect, we can do the warn command to notify the staff member they are being warned.

Demote, if a staff member gets warned enough they get notified that they are being demoted.

**Comment by notcharliee** [comment]
will be coming in a future update 🚀
